config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
  }
  devise_scope :user do
    get "/users/sign_out" => "users/sessions#destroy"
  end
  # users
  resources :users, only: %i[index destroy] do
    get :top, on: :collection
    get :set, on: :member
    get :history, on: :collection
    get :change, on: :member
    get :user_policy, on: :collection
    get :privacy_policy, on: :collection
    get :asct, on: :collection
    get :line_contact, on: :collection
    get :management, on: :collection
    get :activity, on: :member
    get :analytics, on: :collection
  end
  # instabots
    get "instabots" => "instabots#sign_in"
    post "instabots" => "instabots#create"
    post "instabots/auto" => "instabots#auto", as: :instabots_auto
    
  # hashtags
    post "hashtags" => "hashtags#hashtag", as: :hashtag
    delete "hashtags/delete/:id" => "hashtags#destroy", as: :hashtag_destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :instabots, dependent: :destroy
  has_many :hashtags, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  #   flash.now[:notice] = "インスタグラムへ自動的にログイン致します"
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end
  
  # POST /resource/sign_in
  # def create
  #   super
  # end

  def after_sign_in_path_for(resource)
    instabots_path(resource)
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # def after_sign_out_path_for(resource)
  #   new_user_session_path # ログアウト後に遷移するpathを設定
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include InstabotAction
  before_action :redirect, except: %i[top user_policy privacy_policy line_contact management]


  def index
    @auto = Instabot.new
    @hashtag = Hashtag.new
    @key_words = Hashtag.where(user_id: current_user.id).order(created_at: :desc)
    @number = Instabot.find_by(user_id: current_user.id)
    #新規登録の場合（データベースにデータがまだ無い場合）
    if Instabot.exists?(user_id: current_user.id)
       @instabot_rcd = Instabot.find_by(user_id: current_user.id)
       
       session[:instabot]["good"] = @instabot_rcd.good
       session[:instabot]["follow"] = @instabot_rcd.follow
       session[:instabot]["unfollow"] = @instabot_rcd.unfollow

       @good_check = session[:instabot]["good"]
       @follow_check = session[:instabot]["follow"]
       @unfollow_check = session[:instabot]["unfollow"]
    else
       @good_check = session[:instabot]["good"]
       @follow_check = session[:instabot]["follow"]
       @unfollow_check = session[:instabot]["unfollow"]
    end
  end

  
  def destroy
    hash_rcd = Hashtag.find_by(user_id: current_user.id)
    hash_rcd.destroy
  end

  private

  def redirect
    unless user_signed_in?
      redirect_to action: :top
    end
  end

end

app/views/users/activity.html.erb
<head>
    <meta charset="utf-8">
    <meta content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" name="viewport">
    <meta content="ja_JP" property="og:locale">
    <meta content="website" property="og:type">
    <meta content="HASH365[ハッシュ365]" property="og:site_name">
    <meta content="HASH365（ハッシュ365）を使えば、誰でも簡単にフォロワーを増やすことができます。ハッシュタグを指定すると、HASH365があなたのインスタグラムを運用し、フォロワーと投稿へのいいねが増えていきます。" property="og:description">
    <meta content="HASH365（ハッシュ365）を使えば、誰でも簡単にフォロワーを増やすことができます。ハッシュタグを指定すると、HASH365があなたのインスタグラムを運用し、フォロワーと投稿へのいいねが増えていきます。" name="description">
    <meta content="" property="og:title">

    <meta content="noindex, nofollow" name="robots">
    <!-- Google Tag Manager -->
    <script src="https://connect.facebook.net/signals/config/449240842132177?v=2.9.40&amp;r=stable" async=""></script><script src="https://connect.facebook.net/signals/config/1284580028249164?v=2.9.40&amp;r=stable" async=""></script><script async="" src="https://connect.facebook.net/en_US/fbevents.js"></script><script async="" src="https://b92.yahoo.co.jp/search/?p=2CWQL16VV0&amp;label=&amp;ref=https%3A%2F%2Fhash365.net%2Fusers%2F332530%2Factivity&amp;rref=https%3A%2F%2Fhash365.net%2Fusers%2F332530&amp;pt=&amp;item=&amp;cat=&amp;price=&amp;quantity=&amp;r=1623106887.9132404&amp;pvid=bp7pgj3kewlkpn7xllf&amp;tsyjad=1622777194"></script><script type="text/javascript" async="" src="https://static.ads-twitter.com/uwt.js"></script><script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-TD2FGFN"></script><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-TD2FGFN');</script>
    <!-- End Google Tag Manager -->

    <style>
    iframe[name="google_conversion_frame"] { position: absolute; top: 0; }
    </style>
    <script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 819565532;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
    </script><script src="https://googleads.g.doubleclick.net/pagead/viewthroughconversion/819565532/?random=1623106887190&amp;cv=9&amp;fst=1623106887190&amp;num=1&amp;guid=ON&amp;resp=GooglemKTybQhCsO&amp;eid=2505059650&amp;u_h=900&amp;u_w=1440&amp;u_ah=900&amp;u_aw=1440&amp;u_cd=24&amp;u_his=13&amp;u_tz=540&amp;u_java=false&amp;u_nplug=3&amp;u_nmime=4&amp;sendb=1&amp;ig=1&amp;frm=0&amp;url=https%3A%2F%2Fhash365.net%2Fusers%2F332530%2Factivity&amp;ref=https%3A%2F%2Fhash365.net%2Fusers%2F332530&amp;tiba=HASH365%5B%E3%83%8F%E3%83%83%E3%82%B7%E3%83%A5365%5D&amp;hn=www.googleadservices.com&amp;rfmt=3&amp;fmt=4"></script>
    <noscript>
    <div style="display:inline;">
    <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/819565532/?guid=ON&amp;script=0"/>
    </div>
    </noscript>

    <!-- Yahoo Code for your Target List -->
    <script type="text/javascript" language="javascript">
    /* <![CDATA[ */
    var yahoo_retargeting_id = '2CWQL16VV0';
    var yahoo_retargeting_label = '';
    var yahoo_retargeting_page_type = '';
    var yahoo_retargeting_items = [{item_id: '', category_id: '', price: '', quantity: ''}];
    /* ]]> */
    </script>
    <script type="text/javascript" language="javascript" src="//b92.yahoo.co.jp/js/s_retargeting.js"></script>

    <script async="" src="https://s.yimg.jp/images/listing/tool/cv/ytag.js"></script>
    <script>
    window.yjDataLayer = window.yjDataLayer || [];
    function ytag() { yjDataLayer.push(arguments); }
    
    ytag({"type":"ycl_cookie"});
    
    </script>

    <!-- Facebook Pixel Code -->
    <script>
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
    n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
    document,'script','https://connect.facebook.net/en_US/fbevents.js');

    fbq('init', '1284580028249164');
    fbq('addPixelId', '449240842132177');
    fbq('track', "PageView");
    </script>
    <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=1284580028249164&ev=PageView&noscript=1"
    />
    <img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=972151862885900&ev=PageView&noscript=1"
    />
    </noscript>
    <!-- End Facebook Pixel Code -->

    <% content_for :css do %>
        <%= stylesheet_link_tag "history" %>
    <% end %>
    <%# <link rel="stylesheet" media="all" href="/assets/application-f00bd107863a579db136743172e2cfdca1d3358d1b7fe383e98b0d4e7d01600d.css" data-turbolinks-track="false"> %>
    <script src="/assets/application-75f0079c8e098370b4cea2c402e86c3f91ebe8e91eb9a5483574c97458aac8ba.js" data-turbolinks-track="false"></script>
    <meta name="csrf-param" content="authenticity_token">
    <meta name="csrf-token" content="GOK/wRg+Fpj0VT6rQlvAVP/O6HxsQTYHskZZ43kQwdaQ2X0MXEkEuy5wMfiNwMpOMvyH/xnWBygY18V4AjCo0g==">
    <script type="text/javascript" src="https://b97.yahoo.co.jp/pagead/conversion_async.js"></script>
</head>
<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TD2FGFN"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <%= render partial: "layouts/templete/header" %>

    <div class="container">
    <div class="row">
    <div class="col-md-12">
    <div class="pankuzu">
    <a href="/">ホーム</a> » アクションログ
    </div>

    <h1>
    アクションログ
    </h1>
    <p>
    まだアクションがありません
    </p>
    </div>
    </div>
    </div>
    <%= render partial: "layouts/templete/footer" %>


    <script>
        Admin.setPage("activity");
        Admin.init();
    </script>



    <script type="text/javascript" id="">var yahoo_ss_retargeting_id=1000346457,yahoo_sstag_custom_params=window.yahoo_sstag_params,yahoo_ss_retargeting=!0;</script>
    <script type="text/javascript" id="" src="//s.yimg.jp/images/listing/tool/cv/conversion.js"></script>
    <noscript>
    <div style="display:inline;">
    <img height="1" width="1" style="border-style:none;" alt="" src="//b97.yahoo.co.jp/pagead/conversion/1000346457/?guid=ON&amp;script=0&amp;disvt=false">
    </div>
    </noscript><div style="visibility: hidden; position: absolute; top: 0px;">S</div><script src="https://analytics.twitter.com/i/adsct?type=javascript&amp;version=1.1.0&amp;p_id=Twitter&amp;p_user_id=0&amp;txn_id=nwesl&amp;events=%5B%5B%22pageview%22%2Cnull%5D%5D&amp;tw_sale_amount=0&amp;tw_order_quantity=0&amp;tw_iframe_status=0&amp;tpx_cb=twttr.conversion.loadPixels&amp;tw_document_href=https%3A%2F%2Fhash365.net%2Fusers%2F332530%2Factivity" type="text/javascript"></script>
</body>

app/views/users/index.html.erb
<head>
  <meta charset='utf-8'>
  <meta content='width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no' name='viewport'>
  <meta content='ja_JP' property='og:locale'>
  <meta content='website' property='og:type'>
  <meta content='HASH365[ハッシュ365]' property='og:site_name'>
  <meta content='HASH365（ハッシュ365）を使えば、誰でも簡単にフォロワーを増やすことができます。ハッシュタグを指定すると、HASH365があなたのインスタグラムを運用し、フォロワーと投稿へのいいねが増えていきます。' property='og:description'>
  <meta content='HASH365（ハッシュ365）を使えば、誰でも簡単にフォロワーを増やすことができます。ハッシュタグを指定すると、HASH365があなたのインスタグラムを運用し、フォロワーと投稿へのいいねが増えていきます。' name='description'>
  <meta content='' property='og:title'>
  <%= content_for :title do %>
    HASH365[ハッシュ365]
  <% end %>
  <meta content='noindex, nofollow' name='robots'>
  <% content_for :css do %>
    <%= stylesheet_link_tag 'index' %>
  <% end %>

  <meta name="csrf-param" content="authenticity_token" />
  <meta name="csrf-token" content="RFcL6TbCyxD2221mpzn8P3wJWgTzqjC/8Z8zaLUNBh0Z3WssjoxRyZc+mDh6VrI8D1j0ppYg9NvgOQYqnW/qdw==" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
</head>
<body>
  <script crossorigin='anonymous' integrity='sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa' src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>
  <div class='white_pay_modal'>
    <div class='pay_appeal'>
      <h5>
        無料お試し期間が終了しました。
      </h5>
      <p>
        引き続きサービスをご利用いただくには
        <br>
        こちらからプランの変更を行ってください。
      </p>
      <a class='btn btn-appeal' href='/subscriptions?from=modal'>
        プランを変更する
      </a>
      <button class='btn_pay_modal_close'>
        今はしない
      </button>
      <div class='clearfix'></div>
    </div>
  </div>
  <div class='white_recursion_modal'>
    <div class='recursion_appeal'>
      <h5>
        有料プランの期限が間もなく終了します。
      </h5>
      <p>
        引き続きサービスをご利用いただくには
        <br>
        こちらから自動更新の設定を行ってください。
      </p>
      <a class='btn btn-appeal' href='/subscriptions/settings/auto_charge?from=modal'>
        自動更新の設定をする
      </a>
      <button class='btn_recursion_modal_close'>
        今はしない
      </button>
      <div class='clearfix'></div>
    </div>
  </div>
  <div class='white_modal'>
    <div class='tutorial'>
      <div class='step1'>
        <div class='tutorial_header'>
          <h4>
            フォロワーを増やす手順
          </h4>
          <span class='current'>
            STEP1
          </span>
          <span>
            STEP2
          </span>
        </div>
        <h5>
          インスタグラムのアカウントが非公開になっていませんか？
        </h5>
        <p class='tutorial_desc'>
          せっかく自動でいいねを残してもあなたのプロフィールが非公開になっていては、フォロワーは増えません。<br />非公開になっている場合は必ず解除しましょう。<br />
        </p>
        <center>
          <img src='/img/users/insta_tutorial_01_ja.png'>
        </center>
        <button class='btn btn-primary btn-block end_step1'>
          次へ
        </button>
      </div>
      <div class='step2 hide'>
        <div class='tutorial_header'>
          <h4>
            フォロワーを増やす手順
          </h4>
          <span>
            STEP1
          </span>
          <span class='current'>
            STEP2
          </span>
        </div>
        <h5>
          まずはハッシュタグを登録しましょう
        </h5>
        <button class='btn btn-primary btn-block end_step2'>
          ハッシュタグを登録する
        </button>
      </div>
    </div>
  </div>
  <div class='auto_like_start hide' data-text='「アクションログ」をタップしてください。'>
    <p>
      自動いいねが始まりました
    </p>
    <p>
      どんな写真にいいねしているかを確認するには
    </p>
    <p>
      こちらをタップしてみてください。
    </p>
  </div>
  <%= render partial: "layouts/templete/header" %>
  <div class='container'>
      <div class='row'>
        <div class='col-md-12 user_main'>
          <div class='row upper'>
            <div class='col-md-6 col-sm-6'>
              <h2 class='pc_no_margin_top' id='hash_tag'>
                ハッシュタグ設定
              </h2>
              <div class='tag_search'>
                <p class='tag_desc'>
                  こちらに登録したハッシュタグがついている写真に対して自動いいね、フォローを行います。
                  <br>
                  フォローして欲しいユーザーが投稿しそうなハッシュタグを登録しましょう。
                </p>
                <%# ハッシュタグの入力 %>
                    <%= form_with(model: @hashtag, url: hashtag_path, id: :hashform, method: :post, local: true) do |f| %>
                      <%= f.text_field :hashtag, autocomplete: :on, placeholder: "追加したいタグ名を入力してください", class: "hashtag_input" %>
                      <%= f.submit "送信", id: :hashsend %>
                    <% end %>
                <div class='selected_tag'>
                  <span class='title'>
                    登録中のハッシュタグ
                  </span>
                  <ul class="tag_list_wrap">
                    <% if @key_words.present? %>
                      <% @key_words.each do |key_word| %>
                        <li class="tag_list">
                          <%= key_word.hashtag %>
                          <a href="hashtags/delete/<%= key_word.id %>" data-keyword="<%= key_word.hashtag %>" data-method="delete" rel="nofollow" class="fa fa-close delete_keyword"></a>
                        </li>
                      <% end %>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <h2>
            自動アクション<span class="action_warn">（'いいね'処理後自動で 'off' に切り替わります。※電波環境によっては上手く処理がされない場合がございます、その際は再読み込み後操作下さい。）</span>
          </h2>
          <%# いいね、フォロー、アンフォロースイッチ %>
          <div class='auto_setting'>
            <%= form_with(model: @auto, url: instabots_auto_path, method: :post, class: "auto" ,local: true) do |f| %>
              <div class='control-group'>
                <label for='auto_like'>
                  自動いいね
                  (※オンにするとインスタグラムから警告を受けたり、アクションをブロックされる可能性があります)
                </label>
                <div class="switch">
                  <label class="switch__label">
                    <%= f.check_box :good,{ class: "switch__input switch_auto good", checked: @good_check }, checked_value = "true", unchecked_value = "false" %>
                    <span class="switch__content"></span>
                    <span class="switch__circle"></span>
                  </label>
                </div>
              </div>
              <label class='auto_like_target_label'>自動いいね上限設定</label>
              <div class='auto_like_target_radio'>
                <label>
                  <%= f.radio_button :number, 50, class: "number"%>
                  50程度
                </label>
                <label>
                  <%= f.radio_button :number, 100, class: "number"%>
                  100程度
                </label>
                <label>
                  <%= f.radio_button :number, 400, class: "number"%>
                  100以上
                </label>
              </div>
              <div class='control-group'>
                <label for='auto_follow'>
                  自動フォロー
                  (※オンにするとインスタグラムから警告を受けたり、アクションをブロックされる可能性があります)
                </label>
                <div class="switch">
                  <label class="switch__label">
                    <%= f.check_box :follow, { class: "switch__input switch_auto follow", checked: @follow_check }, checked_value="true", unchecked_value="false" %>
                    <span class="switch__content"></span>
                    <span class="switch__circle"></span>
                  </label>
                </div>
              </div>
              <div class='control-group'>
                <label for='auto_unfollow'>
                  登録済みの自動フォロー解除
                </label>
                <div class="switch">
                  <label class="switch__label">
                    <%= f.check_box :unfollow, { class: "switch__input switch_auto unfollow", checked: @unfollow_check }, checked_value="true", unchecked_value="false" %>
                    <span class="switch__content"></span>
                    <span class="switch__circle"></span>
                  </label>
                </div>
              </div>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
  
  <%= render partial: "layouts/templete/footer" %>

  <script>
    Admin.setPage("user");
    Admin.init();
  </script>
</body>